#pragma config(Motor,  port1,           dtr,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          dtl,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	 while(1 == 1)
	 {
   motor[port1]=(vexRT[Ch3];
   motor[port10]=(vexRt[Ch2];


   if(vexRT[Btn5U] == 1)       	//If Button 6U is pressed...
		{
			motor[port5] = 127;  		//...close the gripper.
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 6D is pressed...
		{
			motor[port5] = -127; 		//...open the gripper.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[port5] = 0;    		//...stop the gripper.
		}


		}

}
